In [3]:
import numpy as np

In [4]:
mylist=[1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list=[[1,2],[3,4],[5,6]]

In [7]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.51634552, 0.57830198])

In [19]:
np.random.rand(3,4)

array([[0.37961612, 0.53936301, 0.24895669, 0.18349099],
       [0.89121624, 0.53773788, 0.17301339, 0.31516926],
       [0.40527229, 0.44484563, 0.74662438, 0.2815317 ]])

In [20]:
np.random.randn(5,5)

array([[ 1.45586823, -0.12167189,  1.14860765,  0.88162479,  0.99857587],
       [-0.63647793, -0.98368278,  1.17338632,  0.25871058, -0.94496979],
       [-1.5954401 ,  1.58465589,  0.27102698, -1.24617643, -0.58871503],
       [-0.20876956, -0.17061234,  0.30663101, -0.02459949, -0.25160036],
       [-0.53302066,  1.76187908,  1.31195994,  0.63134943, -0.4361971 ]])

In [41]:
np.random.randint(1,100)

64

In [22]:
np.random.randint(1,100,20)

array([24, 20, 73,  9, 89, 58, 47, 14, 74,  2, 19, 91, 84, 95,  7, 23, 18,
       14,  6, 74])

In [23]:
np.random.randint(1,100,(2,5))

array([[29, 26, 84, 90, 71],
       [11, 21, 48, 27, 19]])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
arr=np.arange(25)

In [26]:
ranarr=np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [34]:
ranarr.max()

39

In [35]:
ranarr.argmax()

7

In [36]:
ranarr.min()

2

In [37]:
ranarr.dtype

dtype('int32')

In [38]:
myarr=np.random.rand(4)

In [39]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])

In [40]:
myarr.dtype

dtype('float64')