In [106]:
import pandas as pd
import numpy as np


In [110]:
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
df=pd.read_csv('C:/Users/Emirhan/Desktop/DeepLearning/Tensorflow2_and_Keras_DeepLearning/TF_2_Notebooks_and_Data/DATA/fake_reg.csv')

In [112]:
df.head()

price     feature1     feature2
0  461.527929   999.787558   999.766096
1  548.130011   998.861615  1001.042403
2  410.297162  1000.070267   998.844015
3  540.382220   999.952251  1000.440940
4  546.024553  1000.446011  1000.338531

In [113]:
sns.pairplot(df)

# Test/Train Split

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X=df[['feature1','feature2']].values

In [42]:
y=df['price'].values

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [44]:
X_train.shape

(700, 2)

In [45]:
X_test.shape

(300, 2)

In [46]:
y_train.shape

(700,)

In [47]:
y_test.shape

(300,)

## Normalizing/Scaling the Data

We scale the feature data.

In [48]:
from sklearn.preprocessing import MinMaxScaler

In [49]:
help(MinMaxScaler)

Help on class MinMaxScaler in module sklearn.preprocessing._data:

class MinMaxScaler(sklearn.base._OneToOneFeatureMixin, sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  MinMaxScaler(feature_range=(0, 1), *, copy=True, clip=False)
 |  
 |  Transform features by scaling each feature to a given range.
 |  
 |  This estimator scales and translates each feature individually such
 |  that it is in the given range on the training set, e.g. between
 |  zero and one.
 |  
 |  The transformation is given by::
 |  
 |      X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
 |      X_scaled = X_std * (max - min) + min
 |  
 |  where min, max = feature_range.
 |  
 |  This transformation is often used as an alternative to zero mean,
 |  unit variance scaling.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_scaler>`.
 |  
 |  Parameters
 |  ----------
 |  feature_range : tuple (min, max), default=(0, 1)
 |      Desired range of transformed data.
 |  
 |  copy : b

In [50]:
scaler=MinMaxScaler()

In [51]:
scaler.fit(X_train)

MinMaxScaler()

In [52]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [53]:
X_train

array([[0.74046017, 0.32583248],
       [0.43166001, 0.2555088 ],
       [0.18468554, 0.70500664],
       ...,
       [0.54913363, 0.79933822],
       [0.2834197 , 0.38818708],
       [0.56282703, 0.42371827]])

In [54]:
X_train.min()

0.0

In [55]:
X_train.max()

1.0

In [56]:
X_test.min()

-0.014108392024525074

In [57]:
X_test.max()

1.0186515935232023

In [58]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense 

In [59]:
help(Sequential)

Help on class Sequential in module keras.engine.sequential:

class Sequential(keras.engine.functional.Functional)
 |  Sequential(layers=None, name=None)
 |  
 |  `Sequential` groups a linear stack of layers into a `tf.keras.Model`.
 |  
 |  `Sequential` provides training and inference features on this model.
 |  
 |  Examples:
 |  
 |  ```python
 |  # Optionally, the first layer can receive an `input_shape` argument:
 |  model = tf.keras.Sequential()
 |  model.add(tf.keras.layers.Dense(8, input_shape=(16,)))
 |  # Afterwards, we do automatic shape inference:
 |  model.add(tf.keras.layers.Dense(4))
 |  
 |  # This is identical to the following:
 |  model = tf.keras.Sequential()
 |  model.add(tf.keras.Input(shape=(16,)))
 |  model.add(tf.keras.layers.Dense(8))
 |  
 |  # Note that you can also omit the `input_shape` argument.
 |  # In that case the model doesn't have any weights until the first call
 |  # to a training/evaluation method (since it isn't yet built):
 |  model = tf.keras.Se

## Creating a Model

There are two ways to create models through the TF 2 Keras API, either pass in a list of layers all at once, or add them one by one.

Let's show both methods (its up to you to choose which method you prefer).

In [60]:
from keras.models import Sequential
from keras.layers import Dense, Activation

### Model - as a list of layers

In [61]:
model = Sequential([Dense(units=2),
                    Dense(units=2),
                    Dense(units=2)
                    ])

### Model - adding in layers one by one

In [62]:
model = Sequential()

model.add(Dense(2))
model.add(Dense(2))
model.add(Dense(2))

Let's go ahead and build a simple model and then compile it by defining our solver

In [63]:
model=Sequential()

model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(4,activation='relu'))

# Final output node for prediction
model.add(Dense(1))

model.compile(optimizer='rmsprop',loss='mse')

In [64]:
model.fit(x=X_train,y=y_train,epochs=250)

Epoch 1/250
22/22 [==============================] - 0s 997us/step - loss: 256561.0781
Epoch 2/250
22/22 [==============================] - 0s 1ms/step - loss: 256384.6875
Epoch 3/250
22/22 [==============================] - 0s 950us/step - loss: 256191.3906
Epoch 4/250
22/22 [==============================] - 0s 950us/step - loss: 255964.0469
Epoch 5/250
22/22 [==============================] - 0s 1ms/step - loss: 255697.7188
Epoch 6/250
22/22 [==============================] - 0s 1ms/step - loss: 255390.3594
Epoch 7/250
22/22 [==============================] - 0s 2ms/step - loss: 255040.2969
Epoch 8/250
22/22 [==============================] - 0s 1ms/step - loss: 254641.5781
Epoch 9/250
22/22 [==============================] - 0s 902us/step - loss: 254191.2188
Epoch 10/250
22/22 [==============================] - 0s 902us/step - loss: 253686.3281
Epoch 11/250
22/22 [==============================] - 0s 950us/step - loss: 253125.6875
Epoch 12/250
22/22 [==============================]

## Evaluation

Let's evaluate our performance on our training set and our test set. We can compare these two performances to check for overfitting.

In [65]:
model.history.history

{'loss': [256561.078125,
  256384.6875,
  256191.390625,
  255964.046875,
  255697.71875,
  255390.359375,
  255040.296875,
  254641.578125,
  254191.21875,
  253686.328125,
  253125.6875,
  252503.65625,
  251811.34375,
  251051.109375,
  250217.59375,
  249304.890625,
  248309.625,
  247223.703125,
  246048.984375,
  244777.4375,
  243406.359375,
  241929.375,
  240342.125,
  238642.375,
  236823.109375,
  234883.84375,
  232807.75,
  230600.78125,
  228260.15625,
  225773.59375,
  223163.84375,
  220397.53125,
  217478.515625,
  214389.578125,
  211153.84375,
  207771.984375,
  204223.546875,
  200515.453125,
  196628.640625,
  192602.578125,
  188381.40625,
  183996.015625,
  179463.59375,
  174773.359375,
  169912.265625,
  164854.03125,
  159695.953125,
  154380.359375,
  148911.78125,
  143318.140625,
  137570.234375,
  131714.5,
  125746.5625,
  119701.6328125,
  113549.8828125,
  107345.234375,
  101053.953125,
  94704.84375,
  88358.234375,
  82043.1171875,
  75713.7109375,
 

In [66]:
loss_df=pd.DataFrame(model.history.history)

In [67]:
loss_df

loss
0    256561.078125
1    256384.687500
2    256191.390625
3    255964.046875
4    255697.718750
..             ...
245      24.662714
246      24.199820
247      24.534525
248      24.462198
249      24.445461

[250 rows x 1 columns]

In [68]:
loss=model.history.history['loss']

In [73]:
sns.lineplot(x=range(len(loss)),y=loss)

<AxesSubplot:title={'center':'Training Loss per Epoch'}, xlabel='feature2', ylabel='Count'>

### Compare final evaluation (MSE) on training set and test set.

These should hopefully be fairly close to each other.

In [74]:
training_score = model.evaluate(X_train,y_train,verbose=0)
test_score = model.evaluate(X_test,y_test,verbose=0)

In [75]:
training_score

23.852014541625977

In [76]:
test_score

25.003082275390625

In [85]:
test_predictions=model.predict(X_test)

10/10 [==============================] - 0s 1ms/step


In [86]:
test_predictions

array([[405.15344],
       [623.5992 ],
       [592.225  ],
       [572.27545],
       [366.31638],
       [579.279  ],
       [514.97064],
       [459.09177],
       [549.2631 ],
       [447.4957 ],
       [611.86633],
       [549.02386],
       [418.9755 ],
       [408.71356],
       [651.1008 ],
       [437.23984],
       [508.55484],
       [660.0333 ],
       [662.6127 ],
       [565.6628 ],
       [333.9331 ],
       [444.74832],
       [382.31644],
       [378.5852 ],
       [566.6853 ],
       [610.69714],
       [532.4229 ],
       [427.76703],
       [655.5193 ],
       [414.0004 ],
       [442.5958 ],
       [485.108  ],
       [438.33444],
       [681.8497 ],
       [424.72037],
       [417.52252],
       [502.04666],
       [550.5587 ],
       [509.66577],
       [395.10428],
       [618.6312 ],
       [416.54025],
       [604.5238 ],
       [445.95926],
       [501.99124],
       [581.713  ],
       [668.85645],
       [490.43225],
       [318.3662 ],
       [485.3972 ],


In [87]:
test_predictions=pd.Series(test_predictions.reshape(300,))

In [88]:
test_predictions

0      405.153442
1      623.599182
2      592.224976
3      572.275452
4      366.316376
          ...    
295    529.039917
296    515.178589
297    609.724426
298    416.886292
299    410.706329
Length: 300, dtype: float32

In [98]:
pred_df = pd.DataFrame(y_test,columns=['Test True Y'])

In [99]:
pred_df

Test True Y
0     402.296319
1     624.156198
2     582.455066
3     578.588606
4     371.224104
..           ...
295   525.704657
296   502.909473
297   612.727910
298   417.569725
299   410.538250

[300 rows x 1 columns]

In [100]:
pred_df = pd.concat([pred_df,test_predictions],axis=1)

In [101]:
pred_df

Test True Y           0
0     402.296319  405.153442
1     624.156198  623.599182
2     582.455066  592.224976
3     578.588606  572.275452
4     371.224104  366.316376
..           ...         ...
295   525.704657  529.039917
296   502.909473  515.178589
297   612.727910  609.724426
298   417.569725  416.886292
299   410.538250  410.706329

[300 rows x 2 columns]

In [102]:
pred_df.columns = ['Test True Y','Model Predictions']

In [103]:
pred_df

Test True Y  Model Predictions
0     402.296319         405.153442
1     624.156198         623.599182
2     582.455066         592.224976
3     578.588606         572.275452
4     371.224104         366.316376
..           ...                ...
295   525.704657         529.039917
296   502.909473         515.178589
297   612.727910         609.724426
298   417.569725         416.886292
299   410.538250         410.706329

[300 rows x 2 columns]

In [105]:
sns.scatterplot(x='Test True Y',y='Model Predictions',data=pred_df)

<AxesSubplot:title={'center':'Training Loss per Epoch'}, xlabel='feature2', ylabel='Count'>

In [114]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [116]:
mean_absolute_error(pred_df['Test True Y'],pred_df['Model Predictions'])

4.002632795443661

In [117]:
mean_squared_error(pred_df['Test True Y'],pred_df['Model Predictions'])

25.00308654938026

In [118]:
# Essentially the same thing, difference just due to precision
test_score

25.003082275390625

In [119]:
#RMSE
test_score**0.5

5.000308218039226

# Predicting on brand new data

What if we just saw a brand new gemstone from the ground? What should we price it at? This is the **exact** same procedure as predicting on a new test data!

In [120]:
# [[Feature1, Feature2]]
new_gem = [[998,1000]]

In [121]:
scaler.transform(new_gem)

array([[0.14117652, 0.53968792]])

In [122]:
new_gem = scaler.transform(new_gem)

In [123]:
model.predict(new_gem)

1/1 [==============================] - 0s 18ms/step


array([[419.47098]], dtype=float32)

## Saving and Loading a Model

In [124]:
from keras.models import load_model

In [125]:
model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'

In [126]:
later_model = load_model('my_model.h5')

In [127]:
later_model.predict(new_gem)

1/1 [==============================] - 0s 44ms/step


array([[419.47098]], dtype=float32)